
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS hpw_core
GO
CREATE TABLE [dbo].[hpw_core](
	[Report Date] [date] NOT NULL,
	[Hybrid L1 Code] [nvarchar](5) NULL,
	[Hybrid L2 Code] [nvarchar](5) NULL,
	[Hybrid L3 Code] [nvarchar](5) NULL,
	[Business Lvl 4 (MRU) Code] [nvarchar](5) NULL,
	[Management Chain - Level 01] [nvarchar](8) NULL,
	[Management Chain - Level 02] [nvarchar](8) NULL,
	[Management Chain - Level 03] [nvarchar](8) NULL,
	[Management Chain - Level 04] [nvarchar](8) NULL,
	[Is Technical Job] [varchar](5) NULL,
	[HC] [int] NULL,
	[Voluntary Attrits] [int] NULL,
	[Executive HC] [int] NULL,
	[NonExecutive HC] [int] NULL,
	[Women Executive HC] [int] NULL,
	[Executive New Hire HC] [int] NULL,
	[Executive New Hire Voluntary Attrits] [int] NULL,
	[Executive Voluntary Attrits] [int] NULL,
	[Executive Involuntary Attrits] [int] NULL,
	[Executive Over 2 Years HC] [int] NULL,
	[Executive Under 2 Years HC] [int] NULL,
	[Executive Over 2 Years Voluntary Attrits] [int] NULL,
	[Executive Under 2 Years Voluntary Attrits] [int] NULL,
	[EXE HC] [int] NULL,
	[EXE Voluntary Attrits] [int] NULL,
	[DIR HC] [int] NULL,
	[DIR Voluntary Attrits] [int] NULL,
	[Technical HC] [int] NULL,
	[Technical Women HC] [int] NULL,
	[TCP HC] [int] NULL,
	[TCP Women HC] [int] NULL,
	[New Hire HC] [int] NULL,
	[Fiscal Year Hire HC] [int] NULL,
	[New Hire Voluntary Attrits] [int] NULL,
	[US Professional HC] [int] NULL,
	[US Professional Asian HC] [int] NULL,
	[US Professional African American HC] [int] NULL,
	[US Professional Hispanic HC] [int] NULL,
	[Salary Annual Rate (USD)] [money] NULL,
	[Mid rate Annual (USD)] [money] NULL,
	[0 to 4 Supervised] [int] NULL,
	[5 to 8 Supervised] [int] NULL,
	[9+ Supervised] [int] NULL,
	[Total Supervised] [int] NULL,
	[Total Supervisors] [int] NULL,
	[US Population] [int] NULL,
	[US Veteran Population] [int] NULL,
	[US Technical HC] [int] NULL,
	[US Asian Technical HC] [int] NULL,
	[US African American Technical HC] [int] NULL,
	[US Hispanic Technical HC] [int] NULL,
	[Women Management HC] [int] NULL,
	[Management HC] [int] NULL,
	[Business Lvl 0 (Company) Code] [nvarchar](5) NULL,
	[Custom View 1] [varchar](15) NULL,
	[Custom View 2] [varchar](15) NULL,
	[Fiscal Quarter] [nchar](6) NULL,
	[Insert Date] [date] NULL
) ON [PRIMARY]
GO
